## NUMPY

In [2]:
import numpy as np

In [7]:
arr = np.array([1, 2, 3, 4, 5])

print(arr)

[1 2 3 4 5]


In [8]:
arr = np.array([[1, 2, 3],[4, 5, 6]])

print(arr)

[[1 2 3]
 [4 5 6]]


In [9]:
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])

print(arr,arr.shape)
print(arr.ndim)


[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]] (2, 2, 3)
3


### Dimensions

In [116]:
arr = np.array(42)
arr_1= np.array([1, 2, 3, 4, 5])
arr_2 = np.array([[1, 2, 3], [4, 5, 6]])
arr_3 = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])

print(arr_1, arr_1.ndim)
print(arr,arr.ndim)
print(arr_2,arr_2.ndim)
print(arr_3, arr_3.ndim)
print(arr_1)
print('number of dimensions :', arr_1.ndim)
print(arr_1[4])
print('Add: ',arr_1[1]+arr_1[4])
print('Multiply',arr_1[1]*arr_1[4])
print('Multiply',arr_1[1]/arr_1[4])


[1 2 3 4 5] 1
42 0
[[1 2 3]
 [4 5 6]] 2
[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]] 3
[1 2 3 4 5]
number of dimensions : 1
5
Add:  7
Multiply 10
Multiply 0.4


### Indexing

In [16]:
print("2nd element on 1st row:",arr_2[1,1])
print('Last element from 2nd dim: ', arr_2[1, -1])
print("third element of the second array of the first array",arr_3[0,1,2])

2nd element on 1st row: 5
Last element from 2nd dim:  6
third element of the second array of the first array 6


### Slicing

In [60]:
arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[1:5])
print(arr[4:])
print(arr[:4])
print(arr[-3:-1])
print(arr[1:5:2])
print(arr[::2])
print(arr_2[1, 1:4])
print(arr_2[0:2, 1:4])
print(arr.dtype)


[2 3 4 5]
[5 6 7]
[1 2 3 4]
[5 6]
[2 4]
[1 3 5 7]
[5 6]
[[2 3]
 [5 6]]
int32


### Data Type

In [62]:

arr = np.array(['apple','banana','cherry'])
print(arr.dtype)
np.array([1, 2, 3, 4]).astype(float).dtype

print(arr)
print(arr.dtype)
arr = np.array([1, 2, 3, 4], dtype='i8')

print(arr)
print(arr.dtype)


<U6
['apple' 'banana' 'cherry']
<U6
[1 2 3 4]
int64


### Copy&View

In [66]:

x = arr.copy()
arr[0] = 42

print(arr)
print(x)

x = arr.view()
arr[0] = 42

print(arr)
print(x)
x = arr.copy()
y = arr.view()

print(x.base)
print(y.base)

[42  2  3  4]
[42  2  3  4]
[42  2  3  4]
[42  2  3  4]
None
[42  2  3  4]


### Shape&Reshape

In [89]:
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8],[5, 6, 7, 8],[5, 6, 7, 8],[5, 6, 7, 8],])
print(arr.shape)


arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])
newarr = arr.reshape(4, 3)
print(newarr)


arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])
newarr = arr.reshape(2, 3, 2)
print(newarr)

(5, 4)
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


### Loop

In [87]:
for x in arr_1:
  print(x)
for x in arr_2:
  print(x)
for x in arr_2:
  for y in x:
    print(y)

1
2
3
4
5
[1 2 3]
[4 5 6]
1
2
3
4
5
6


### Concatenation

In [88]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
arr = np.concatenate((arr1, arr2))
print(arr)

[1 2 3 4 5 6]


In [97]:
newarr = np.array_split(arr_1, 3)

for x in range(3):
    print(newarr[x])
    

[1 2]
[3 4]
[5]


### Where & Sort

In [104]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])

x = np.where(arr%2 == 0)

print(x)
arr = np.array(['banana', 'cherry', 'apple'])

print(np.sort(arr))
arr = np.array([[3, 2, 4], [5, 0, 1]])

print(np.sort(arr))

(array([1, 3, 5, 7], dtype=int64),)
['apple' 'banana' 'cherry']
[[2 3 4]
 [0 1 5]]


### Mean, Meadian

In [110]:
arr = np.array([1,2,3,4,4,4,5,5,6,7,6,8,4,3,2,4,6,7])
print(np.sort(arr))
print(np.mean(arr))
print(np.median(arr))


[1 2 2 3 3 4 4 4 4 4 5 5 6 6 6 7 7 8]
4.5
4.0


### Transpose of Array


In [113]:
print(arr_2)
print(arr_2.transpose())

[[1 2 3]
 [4 5 6]]
[[1 4]
 [2 5]
 [3 6]]


### T&T Lab Assignment - 5

In [3]:
x_zeroes = np.zeros([2,3], dtype=int)
x_ones = np.ones([2,3], dtype=int)
x_arange = np.arange(1,10,4)
x_tuple = np.array((1,2,3,4,56))
x_lists = np.array([2,3,4,5,6])
print(x_zeroes)
print(x_ones)
print(x_arange)
print(x_tuple)
print(x_lists)

[[0 0 0]
 [0 0 0]]
[[1 1 1]
 [1 1 1]]
[1 5 9]
[ 1  2  3  4 56]
[2 3 4 5 6]


In [4]:
x1 = np.array([[1,2,3],[3,4,5]])
x2 = np.array([[4,5,6],[6,7,8]])
A = np.add(x1,x2)
B = np.subtract(x1,x2)
C = np.multiply(x1, x2)
D = np.divide(x1, x2)
print("The addition :: ", A)
print("The subtraction :: ", B)
print("The multiplication :: ", C)
print("The division :: ", D)


The addition ::  [[ 5  7  9]
 [ 9 11 13]]
The subtraction ::  [[-3 -3 -3]
 [-3 -3 -3]]
The multiplication ::  [[ 4 10 18]
 [18 28 40]]
The division ::  [[0.25       0.4        0.5       ]
 [0.5        0.57142857 0.625     ]]
